### ISSUE TITLE
Different WARs from the same project.clj

### ISSUE THREAD

**Issue by giorgio-v** [immutant/lein-immutant#112]
I’m in the process of consolidating a bunch of project under a single repository. Well, that’s the intention, because I’d need to create two different WARs with a different set of classes and maybe other settings as well.

Is there a way to do this?

Thank you for any help you can provide.

**Comment by tobias** [comment]
Hi @giorgio-v - If you need different code in each war, I think you
have at least two options (there are probably more, these are the
first two that come to mind):

1. Separate the code in to different source folders, and set
   `:source-paths` to all of them in `project.clj` (run `lein sample`
   to see the docs for that option). Then set `:source-paths` in a
   profile for each war you need to build, with just the src dir(s)
   for that war. In that same profile, include any other settings
   specific to that war. Then build the war with:
   `lein with-profile my-profile immutant war`

2. Break the project up as sub-projects, using
   [lein-modules](https://github.com/jcrossley3/lein-modules), then
   build the war from the appropriate sub-project. This is definitely
   more work than (1), but may be appropriate for your application
   structure, I don't know.

If either of those don't work for you, either due to a failure in
lein-immutant, or for some architectural reason, I'm happy to continue
this discussion.

**Comment by giorgio-v** [comment]
Awesome. We’ll try the first approach and see if it could work for us.

Thank you, Tobias.

**Comment by giorgio-v** [comment]
It works! Thanks for suggestions.
